### ISSUE TITLE
🚀 Publish `1.0.1`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#145]
## Overview

* Publish version as `1.0.1`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #146
- [x] Publish.
- [x] #148
- [x] Push version tag `1.0.1` on main

## npm login to GitHub Packages before publishing

- [x] get login password from your GitHub settings
Go to → https://github.com/settings/tokens
- [x] copy your `personal access token` created
- [x] run in terminal
    ```
    % npm login --registry=https://npm.pkg.github.com/

    Username: your-github-account-in-lower-case-only
    Password:
    Email: your.mail.account@gmail.com
    Logged in as [your-name] on https://npm.pkg.github.com/.
    ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `9fe881d`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-inspector@1.0.1
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                      
  npm notice 5.8kB README.md                    
  npm notice 258B  index.js                     
  npm notice 3.4kB lib/ESLintInspector.js       
  npm notice 1.5kB lib/FileLintAnalyzer.js      
  npm notice 2.8kB lib/LintAnalyzer.js          
  npm notice 1.4kB lib/tools/LintKeyExtractor.js
  npm notice 1.0kB package.json                 
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-inspector          
  npm notice version:       1.0.1                                    
  npm notice filename:      @openreachtech/eslint-inspector-1.0.1.tgz
  npm notice package size:  5.3 kB                                   
  npm notice unpacked size: 17.3 kB                                  
  npm notice shasum:        8fed1e6cd6c416d199c16c5dc3f0dd5bf8eae9aa 
  npm notice integrity:     sha512-3fzGG24tLPxSA[...]DrOQTmQTfEcPQ== 
  npm notice total files:   8                                        
  npm notice 
  + @openreachtech/eslint-inspector@1.0.1
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
