### ISSUE TITLE
🚀 Publish `1.0.2`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#179]
## Overview

* Publish version as `1.0.2`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #180
- [x] Publish.
- [x] #182
- [x] Push version tag `1.0.2` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `2304311`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-inspector@1.0.2
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                      
  npm notice 6.2kB README.md                    
  npm notice 258B  index.js                     
  npm notice 3.5kB lib/ESLintInspector.js       
  npm notice 1.4kB lib/FileLintAnalyzer.js      
  npm notice 3.0kB lib/LintAnalyzer.js          
  npm notice 2.3kB lib/tools/LintKeyExtractor.js
  npm notice 1.1kB package.json                 
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-inspector          
  npm notice version:       1.0.2                                    
  npm notice filename:      @openreachtech/eslint-inspector-1.0.2.tgz
  npm notice package size:  5.6 kB                                   
  npm notice unpacked size: 18.7 kB                                  
  npm notice shasum:        65f1e999f30363b5fb749b6cd1acb8b52317c9e5 
  npm notice integrity:     sha512-miQi57pwWBx4y[...]ZhiBFmShXblAg== 
  npm notice total files:   8                                        
  npm notice 
  + @openreachtech/eslint-inspector@1.0.2
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
