### ISSUE TITLE
✅ Update `eslint-config-openreachtech`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#187]
## Overview

* Update `eslint-config-openreachtech` version to `2.0.0`

## Tasks

- [x] Update `eslint-config-openreachtech` version to `2.0.0`
- [x] Fix test cases for `2.0.0` rules
- [x] Fix linted code
