### ISSUE TITLE
🚀 Publish `1.0.3`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#239]
## Overview

* Publish version as `1.0.3`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #240
- [x] Publish.
- [x] #242
- [x] Push version tag `1.0.3` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `26efc67`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-inspector@1.0.3
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                      
  npm notice 7.1kB README.md                    
  npm notice 258B  index.js                     
  npm notice 3.6kB lib/ESLintInspector.js       
  npm notice 1.4kB lib/FileLintAnalyzer.js      
  npm notice 3.2kB lib/LintAnalyzer.js          
  npm notice 2.3kB lib/tools/LintKeyExtractor.js
  npm notice 1.0kB package.json                 
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-inspector          
  npm notice version:       1.0.3                                    
  npm notice filename:      @openreachtech/eslint-inspector-1.0.3.tgz
  npm notice package size:  6.0 kB                                   
  npm notice unpacked size: 19.9 kB                                  
  npm notice shasum:        dbce4718202e17f702de3374a05c079fd0c91328 
  npm notice integrity:     sha512-WuJgh/Anw0a4M[...]Qo7rw+JIk0Zeg== 
  npm notice total files:   8                                        
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com (dry-run)
  + @openreachtech/eslint-inspector@1.0.3
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
