### ISSUE TITLE
💪 Retake `LintKeyExtractor` according to new file structure

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#279]
## Overview

* Retake `LintKeyExtractor` according to new file structure

## Tasks

- [x] 💪 Purge `#groupedRuleIds` and `#plugins`
- [x] 🧹 Remove `LintKeyExtractor#getPluginName()`
- [x] 💪 Retake `LintKeyExtractor#extractRuleId()` with new file structure
- [x] 💪 Retake `LintKeyExtractor#extractMessageId()` with new file structure
