### ISSUE TITLE
🚀 Publish `1.1.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#280]
## Overview

* Publish version as `1.1.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #281
- [x] Publish.
- [x] #283
- [x] Push version tag `1.1.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `23af34b`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-inspector@1.1.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                      
  npm notice 7.1kB README.md                    
  npm notice 258B  index.js                     
  npm notice 3.6kB lib/ESLintInspector.js       
  npm notice 1.6kB lib/FileLintAnalyzer.js      
  npm notice 3.2kB lib/LintAnalyzer.js          
  npm notice 2.8kB lib/tools/LintKeyExtractor.js
  npm notice 1.0kB package.json                 
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-inspector         
  npm notice version:       1.1.0                                   
  npm notice filename:      openreachtech-eslint-inspector-1.1.0.tgz
  npm notice package size:  6.1 kB                                  
  npm notice unpacked size: 20.6 kB                                 
  npm notice shasum:        2eecc5c1eb3495d92ce78d03b2e587a6faf89526
  npm notice integrity:     sha512-09W29Z8/nJ2hG[...]Rd1zvhFMold0w==
  npm notice total files:   8                                       
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/eslint-inspector@1.1.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
