### ISSUE TITLE
⚙️ Add `eslint.config.js` as stub to avoid error of GitHub Actions

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#291]
## Overview

* Add `eslint.config.js` as stub to avoid error of GitHub Actions

## Tasks

- [x] ⚙️ Add `eslint.config.js` as stub
- [x] ~⚙️ Add Jest plugin of ESLint as stub~
- [x] ~⚙️ Add JSDoc plugin of ESLInt as stub~
- [x] Restore some lint errors and warnings
- [x] ⚙️ Reinstate `npm run lint` in GitHub Workflows
