### ISSUE TITLE
⚙️ Update devDependencies packages

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#331]
## Overview

* ⚙️ Update devDependencies packages

## Tasks

- [x] Update `estlint-plugin-jest` version to `^28.5.0`
- [x] Update `eslint` version to `^9.2.0`
- [x] Update `@types/jest` to `^29.5.12`
