### ISSUE TITLE
🚀 Publish `2.1.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#370]
## Overview

* Publish version as `2.1.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #371
- [x] Publish.
- [x] #373
- [x] Push version tag `2.1.0` on main

## npm login to GitHub Packages before publishing

* Procedure login as follows:
  1. get login password from your GitHub settings<br>Go to → https://github.com/settings/tokens
  2. copy your `personal access token` created
  3. run in terminal
      ```
      % npm login --registry=https://npm.pkg.github.com/

      Username: your-github-account-in-lower-case-only
      Password:
      Email: your.mail.account@gmail.com
      Logged in as [your-name] on https://npm.pkg.github.com/.
      ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `ce456e6`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm login user

  ```
  npm whoami --registry https://npm.pkg.github.com
  ```

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-inspector@2.1.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                      
  npm notice 7.6kB README.md                    
  npm notice 258B  index.js                     
  npm notice 325B  index.mjs                    
  npm notice 3.6kB lib/ESLintInspector.js       
  npm notice 1.4kB lib/FileLintAnalyzer.js      
  npm notice 3.2kB lib/LintAnalyzer.js          
  npm notice 1.8kB lib/tools/LintKeyExtractor.js
  npm notice 1.2kB package.json                 
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-inspector         
  npm notice version:       2.1.0                                   
  npm notice filename:      openreachtech-eslint-inspector-2.1.0.tgz
  npm notice package size:  6.2 kB                                  
  npm notice unpacked size: 20.4 kB                                 
  npm notice shasum:        9ecf4cdc7f30683d24142ce9770b45ffadad5b76
  npm notice integrity:     sha512-BNfu4019Jsz/v[...]zKzpiAdq9TadQ==
  npm notice total files:   9                                       
  npm notice 
  npm notice Publishing to https://npm.pkg.github.com with tag latest and default access (dry-run)
  + @openreachtech/eslint-inspector@2.1.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [ ] `npm publish`
