### ISSUE TITLE
🚀 Publish `1.0.0`

### ISSUE THREAD

**Issue by StewEucen** [openreachtech/eslint-inspector#75]
## Overview

* Publish version as `1.0.0`.

* See [[Renchan] Publish to GitHub Packages - Kibela](https://openreachtech.kibe.la/notes/5722)

## Tasks

- [x] #81
- [x] Publish.
- [x] #87
- [x] Push version tag `1.0.0` on main

## npm login to GitHub Packages before publishing

- [x] get login password from your GitHub settings
Go to → https://github.com/settings/tokens
- [x] copy your `personal access token` created
- [x] run in terminal
    ```
    % npm login --registry=https://npm.pkg.github.com/

    Username: your-github-account-in-lower-case-only
    Password:
    Email: your.mail.account@gmail.com
    Logged in as [your-name] on https://npm.pkg.github.com/.
    ```

### 1. Check Commit Hash to Publish

- [x] git log --graph --oneline --decorate --all
- [x] target commit as: `b2ba72b`

### 2. Confirm Work to Publish

- [x] To export new features correctly.
- [x] Confirm version in `package.json`
- [x] Confirm version in `package-lock.json`

### 3. Publish

- [x] Confirm publishing commit with `--dry-run`

  ```
  npm publish --dry-run
  ```

  ```
  % npm publish --dry-run
  npm notice 
  npm notice 📦  @openreachtech/eslint-inspector@1.0.0
  npm notice === Tarball Contents === 
  npm notice 1.1kB LICENSE                
  npm notice 4.0kB README.md              
  npm notice 258B  index.js               
  npm notice 3.1kB lib/ESLintInspector.js 
  npm notice 839B  lib/FileLintAnalyzer.js
  npm notice 1.0kB lib/LintAnalyzer.js    
  npm notice 1.0kB package.json           
  npm notice === Tarball Details === 
  npm notice name:          @openreachtech/eslint-inspector          
  npm notice version:       1.0.0                                    
  npm notice filename:      @openreachtech/eslint-inspector-1.0.0.tgz
  npm notice package size:  4.0 kB                                   
  npm notice unpacked size: 11.3 kB                                  
  npm notice shasum:        8fc69d10e224252cf74aaf477b396a17ca0603d1 
  npm notice integrity:     sha512-k5UefjqcAsPFG[...]cl2j9SJHlb6Mg== 
  npm notice total files:   7                                        
  npm notice 
  + @openreachtech/eslint-inspector@1.0.0
  ```

- [x] Check log of `--dry-run` by other member before actual publishing.
- [x] `npm publish`
